### ISSUE TITLE
Artifacts are copied without extension

### ISSUE THREAD

**Issue by nanestev** [JetBrains/teamcity-aws-codepipeline-plugin#4]
I'm using the TC plugin for CodePipeline in a simple pipeline that polls changes from Github for its Source stage, pass them to TeamCity to be built for its Build stage, and then deploy build artifacts with CloudFromation in its Deploy stage. The problem is that when artifacts are uploaded after the final step in TC their file extensions are not preserved. 

![snapshot](http://image.prntscr.com/image/2555762f845d4a66a2bb5512d1eefde9.png)

Thus my deploy stage fails (actual stage is ok, but deployment scripts on the instance fail) with the following message: 
> Unsupported source file (not zip or tarball): https://s3.amazonaws.com/codepipeline-*************/Influence-staging/InfWebBld/h8Mhko2

as the sources element of the AWS::CloudFormation::Init resource in my CF template expects supported file extension. 

Is there a quick way to sort this out?
Thanks.

Edit: I can see [here](https://github.com/JetBrains/teamcity-aws-codepipeline-plugin/blob/master/aws-codepipeline-agent/src/main/java/jetbrains/buildServer/codepipeline/CodePipelineBuildListener.java#L165) why it is happening, but it looks to me that it's like that by design. Am I right?

**Comment by vbedrosova** [comment]
Hi, @nanestev thank you for the feedback. 
I've recently changed the way output artifacts are uploaded, so please download the latest aws-codepipeline-plugin [version](https://teamcity.jetbrains.com/project.html?projectId=TeamCityPluginsByJetBrains_AwsDeveloperToolsSupport_AwsCodePipelinePlugin&tab=projectOverview) and change your runner settings to publish the artifacts directly to %codepipeline.artifact.output.folder% according to the updated[ doc](https://confluence.jetbrains.com/display/TW/AWS+CodePipeline+Plugin#Action_input_and_output_artifacts).
Please let me know if you have any problems.

**Comment by nanestev** [comment]
Hi @vbedrosova, that's exactly the doc I was following together with the [Building End-to-End Continuous Delivery and Deployment Pipelines in AWS and TeamCity](https://aws.amazon.com/blogs/devops/building-end-to-end-continuous-delivery-and-deployment-pipelines-in-aws-and-teamcity/) tutorial. The installed version of the plugin on my TC server is the 10.0 from three days ago. I can see that last build is on 30th of November, so I have installed the latest version of the plugin.

**Comment by vbedrosova** [comment]
@nanestev ok, looks like you are are running the latest version and the issue is that the s3Location.getObjectKey() doesn't contain file extension by design as you have mentioned. So far I don't know any way to workaround it. I will pass the issue to the CodePipeline team.

**Comment by nanestev** [comment]
Thanks. Please, let me know if I can be of any help while you're resolving this.

**Comment by belltimo** [comment]
Hi @nanestev,

I'm from the AWS CodePipeline team, just letting you know that we're looking into this.

Is it possible for you to email me your AWS account ID and pipeline name? That may help us track down some logs. My email is my GitHub username @ amazon.com.

**Comment by nanestev** [comment]
Hi @belltimo,
Sure, will email you the details in a sec.

**Comment by nanestev** [comment]
Thanks to @belltimo I managed to resolve this. The problem was not with missing file extension, but with incorrect downloaded content instead of the zipped artifacts due to old version of cfn-init and bad request being sent to S3.
