### ISSUE TITLE
Build parameters did not show up after plugin installation

### ISSUE THREAD

**Issue by jkinkead** [JetBrains/teamcity-aws-codepipeline-plugin#5]
I installed version `SNAPSHOT-201612212347` of plugin onto an existing TeamCity server (version `10.0.2`) per the instructions [on the plugin page](https://confluence.jetbrains.com/display/TW/AWS+CodePipeline+Plugin).

After installation, the parameters `codepipeline.artifact.input.folder` and `codepipeline.artifact.output.folder` weren't set in the system or on any build agents, which wasn't what I expected when reading the following on the plugins page:

> The folder is specified by the codepipeline.artifact.input.folder configuration parameter which is by default %system.teamcity.build.tempDir%/CodePipeline/input.

> ... specified by the codepipeline.artifact.output.folder configuration parameter (which is %system.teamcity.build.tempDir%/CodePipeline/output by default)

That sounds an awful lot like these should be available without me having to configure them, which is what I ended up doing.

This seems like it's either a bug, or else the documentation is misleading.

**Comment by vbedrosova** [comment]
Hi, @jkinkead the codepipeline.artifact.input.folder and codepipeline.artifact.output.folder configurations parameters are available to the runner during the build on agent and you may reference them using %...% symbols in you build script or other build runner setting, does this work for you?

**Comment by jkinkead** [comment]
I think my issue is that I was unclear that these are only available when this is executed from CodePipeline, and have to be set manually for test executions. It was very confusing as a TeamCity novice trying to figure out why my builds weren't able to be executed when I was testing, and why I was getting warnings about my configuration!

I think it's all resolved now, though.
